language: node_js
node_js: "12"
branches:
  only:
    - master
    - main
cache:
  directories:
    - node_modules
services:
  - npm
  - mysql
before_install:
  - npm i
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
